package v1

type STEP_TYPE string
const (
	BUILD=STEP_TYPE("BUILD")
	DEPLOY=STEP_TYPE("DEPLOY")
)

const  (
	TEKTON_NAMESPACE="TEKTON"
)


type VARIABLE_REFERNECE_TYPE string
const (
	SECRET=VARIABLE_REFERNECE_TYPE("SECRET")
	CONFIG_MAP=VARIABLE_REFERNECE_TYPE("CONFIG_MAP")
)